sudo: required
services:
  - docker

before_install:
  - docker build -t pkingo/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t pkingo/multi-client ./client 
  - docker build -t pkingo/multi-nginx ./nginx
  - docker build -t pkingo/multi-server ./server
  - docker build -t pkingo/multi-worker ./worker
  # Log in to the docker CLI
  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push pkingo/multi-client
  - docker push pkingo/multi-nginx
  - docker push pkingo/multi-server
  - docker push pkingo/multi-worker

  